### ISSUE TITLE
User Guide Missing

### ISSUE THREAD

**Issue by JCGithu** [eleclab-rpi/8INCH_HDMI_1600x480#1]
Hi, 

You have your user guides uploaded for other products, but not this one. Could you add it please? Thanks

**Comment by eleclab-rpi** [comment]
Thank you very much for your feedback, ElecLab 8inch HDMI Touchscreen Display USER GUIDE.pdf has been uploaded to https://github.com/eleclab-rpi/8INCH_HDMI_1600x480 project.
Best Wishes!



***@***.***
 
From: Colloquial
Date: 2023-08-03 04:00
To: eleclab-rpi/8INCH_HDMI_1600x480
CC: Subscribed
Subject: [eleclab-rpi/8INCH_HDMI_1600x480] User Guide Missing (Issue #1)
Hi,
You have your user guides uploaded for other products, but not this one. Could you add it please? Thanks

**Comment by JCGithu** [comment]
Thank you for such a quick reply! Really helpful

**Comment by eleclab-rpi** [comment]
You are so kind, any suggestion and communication can make us learn more.
Best Wishes!



***@***.***
 
From: Colloquial
Date: 2023-08-03 16:36
To: eleclab-rpi/8INCH_HDMI_1600x480
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/8INCH_HDMI_1600x480] User Guide Missing (Issue #1)
Thank you for such a quick reply! Really helpful
